# Generated by Django 3.2.6 on 2021-08-16 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receitas_App', '0006_auto_20210816_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 16, 16, 28, 11, 897615)),
        ),
    ]
